import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useState,useEffect,useLayoutEffect } from 'react'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Banner from '../components/home/Banner'
import {nearbyType} from '../types/nearby'
import Nearby from '../components/home/Nearby'
import MediumCard from '../components/home/MediumCard'
import LargerCart from '../components/home/LargerCart'
import { InferGetStaticPropsType } from 'next'
import { mediumCartType } from '../types/mediumCart'
import { useDispatch, useSelector } from 'react-redux'


const Index = ({smallCarts,mediumCartsApi}:InferGetStaticPropsType<typeof getStaticProps>) => {

 
  const [nearby, setNearby] = useState([] as nearbyType[])
  const [mediumCarts, setMediumCarts] = useState([] as mediumCartType[])

  useLayoutEffect(() => {
      setNearby(smallCarts)
      setMediumCarts(mediumCartsApi)
  }, [])




  return (
    <div>
    <Head>
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
      <div>
          <Header container={'my-container-big'}/>
          <Banner/>
          <Nearby nearby={nearby}/>
          <MediumCard mediumCarts={mediumCarts}/>
          <LargerCart
           img='https://links.papareact.com/4cj'
           title="The Greatest Outdoors"
           description="Wishlist created by Airbnb"
           btn_text="Get Inspired"
           />
           <Footer container={'my-container-big'}/>
      </div>
      </div>
  )
}



export async function getStaticProps<GetStaticProps>() {

  const smallCarts = await fetch('https://links.papareact.com/pyp')
  .then(res=>res.json())


  const mediumCartsApi = await fetch('https://links.papareact.com/zp1')
      .then(res=>res.json())
  
  return{
      props:{
          smallCarts,
          mediumCartsApi
      }
  }    

}



export default Index

