import type { NextPage } from 'next'
import Head from 'next/head'
import Home from '../pages/home/index'

const Index: NextPage = () => {
  return (
    <div>
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Home/> */}
    </div>
  )
}

export default Index
